---
# tasks file for roles/network

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: mtr
  yum:
    name: mtr
    state: present

- name: Configuration inetRouter
  include_tasks: inetRouter.yml
  when: ansible_hostname == "inetRouter"

- name: Configuration centralRouter
  include_tasks: centralRouter.yml
  when: ansible_hostname == "centralRouter"
  
- name: Configuration centralServer
  include_tasks: centralServer.yml
  when: ansible_hostname == "centralServer"
  
- name: Configuration office1Router
  include_tasks: office1Router.yml
  when: ansible_hostname == "office1Router"
  
- name: Configuration office1Server
  include_tasks: office1Server.yml
  when: ansible_hostname == "office1Server"
  
- name: Configuration office2Router
  include_tasks: office2Router.yml
  when: ansible_hostname == "office2Router"
  
- name: Configuration office2Server
  include_tasks: office2Server.yml
  when: ansible_hostname == "office2Server"
