---
# tasks file for roles/network

- name: Set ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    reload: yes
    
- name: Set DEFROUTE=No
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DEFROUTE='
    line: DEFROUTE="no"
  notify:
    - restart network

- name: GATEWAY
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    insertafter: 'NETMASK'
    regexp: '^GATEWAY='
    line: 'GATEWAY=10.10.2.1'
    state: present
  notify:
    - restart network

- name: start network
  systemd:
    name: network
    state: restarted
